# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0007_auto_20150921_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showerthought',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
