# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('texts', '0008_auto_20160503_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showerthought',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
